
spring:
  mail:
    #QQ邮件服务地址
    host: smtp.qq.com
    #发件邮箱
    username:
    #密码（授权码）
    password:
    #默认编码utf-8
    default-encoding: UTF-8

server:
  port: 8085

  #eureka注册中心
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8761/eureka/

    #本应用的名称
  application:
    name: mail
